# 开发环境配置
app:
  name: "积水车辆检测系统 (开发版)"
  version: "1.0.0-dev"
  debug: true
  
server:
  host: "0.0.0.0"
  port: 8000
  workers: 1
  reload: true
  
models:
  directory: "./models"
  cache_size: 2
  preload: false
  
security:
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:80"
    - "http://127.0.0.1:3000"
  max_file_size: 10485760  # 10MB
  rate_limit: 1000  # requests per minute (宽松限制)
  
logging:
  level: "debug"
  format: "colored"
  
monitoring:
  enable_metrics: false