# 生产环境配置
app:
  name: "积水车辆检测系统"
  version: "1.0.0"
  debug: false
  
server:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  
models:
  directory: "/app/models"
  cache_size: 4
  preload: true
  
security:
  cors_origins:
    - "https://yourdomain.com"
    - "https://www.yourdomain.com"
  max_file_size: 10485760  # 10MB
  rate_limit: 100  # requests per minute
  
logging:
  level: "info"
  format: "json"
  file: "/app/logs/app.log"
  
monitoring:
  enable_metrics: true
  metrics_port: 9090
  health_check_interval: 30